### ISSUE TITLE
olympus.itunes.apple.com no longer exists?

### ISSUE THREAD

**Issue by TheGeekPharaoh** [eternalstorms/ESSAppStoreConnectAPI#1]
Great project!!  I'd love to use this code in my automation workflow.  However, the host that you get your authServiceKey from -- olympus.itunes.apple.com -- no longer exists.  Or, at the very least, can no longer be resolved (DNS fails, etc.).  Has it been replaced?  Any idea?

**Comment by eternalstorms** [comment]
Hi, thank you :)
Yes, I haven't been able to update the project yet. The new URL, instead of olympus.itunes.apple.com, is https://appstoreconnect.apple.com/olympus/v1/app/config?hostname=itunesconnect.apple.com .
I hope that helps!

All the best to you,
- Matthias
